### PR TITLE
Disruption index visualization

### PR DESCRIPTION
**Pull request by ben-heil**
This PR adds the infrastructure to calculate the disruption index for networkx graphs, and visualizes their results in a notebook.
Here are representative images of the results, since plotly still doesn't play well with large data or Github
Screenshot from 2022-06-28 10-18-55
Screenshot from 2022-06-28 10-18-19
Screenshot from 2022-06-28 10-18-02

Changes:
- Add the `all_nodes_disruption_index` function to run the disruption index on all nodes in a graph
- Switch from `in_edges` and `out_edges` idiom to `successors` and `predecessors` idiom
- Fix a bug where missing citations would cause disruption indices of +- 2
- Add the disruption index to `run_metrics_on_graph.py`

### CODE REVIEW

**Review by jjc2718 — APPROVED** [review]
Looks good! I added a few comments on ReviewNB.

I do think some kind of stability analysis would be interesting. My intuition is that disruption index might not be as stable as PageRank - my understanding is that to be in type "j", a paper only has to cite one of the focal paper's successors, which could happen incidentally sometimes (correct me if I'm wrong). Maybe a variant where you require some proportion of the focal paper's successors to be cited could be more stable?

Anyway, just throwing out ideas. I think disruption index is a neat concept, but I think there are lots of ways you could tweak it, if you wanted to (or needed it to be more stable, etc).

**Comment by ben-heil** [comment]
<p>The disruption index is a ratio where the denominator depends on the paper's citation count and the citation count of the papers it cites. If that number is e.g. 2, then it the disruption index can only be -1, -.5, 0, .5, or 1. Since the number of papers with few citations is very large the bins for corresponding to small denominators are also large</p>

---

 <a href='https://app.reviewnb.com/greenelab/indices/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ben-heil** [comment]
<p>Networks with the <code>first_degree</code> tag include all citations where either paper has the MeSH term, where the other networks only include citations where both papers are part of the MeSH term</p>

---

 <a href='https://app.reviewnb.com/greenelab/indices/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ben-heil** [comment]
<p>Yeah, it would be interesting to look at. The distribution of disruption index in the "Large teams develop and small teams disrupt science and technology" paper is actually left heavy instead of right-heavy, and tails off at the ends. I'll have to take a closer look at their paper inclusion criteria</p>

---

 <a href='https://app.reviewnb.com/greenelab/indices/pull/5/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ben-heil** [comment]
> I do think some kind of stability analysis would be interesting. My intuition is that disruption index might not be as stable as PageRank - my understanding is that to be in type "j", a paper only has to cite one of the focal paper's successors, which could happen incidentally sometimes (correct me if I'm wrong). Maybe a variant where you require some proportion of the focal paper's successors to be cited could be more stable?
> 
> Anyway, just throwing out ideas. I think disruption index is a neat concept, but I think there are lots of ways you could tweak it, if you wanted to (or needed it to be more stable, etc).

I agree, I think PageRank will be more stable, and I also think that disruption index would be more stable if it didn't include papers with few citations

**Pull request merged**
